### ISSUE TITLE
yfeed <> socialhub

### ISSUE THREAD

**Issue by phoebusryan** [yakamara/redaxo_yfeed#11]
Hi,
schönes Addon. Nur schade, dass es parallel entwickelt wurde zu meinem Socialhub (https://github.com/phoebusryan/rex_socialhub) ... wobei es ja eigentlich von Sascha war und ich es grundlegend überarbeitet habe. Meins kann Instagram schon, dafür kein RSS.

Solltest du das Addon hier weiterentwickeln (und danach sieht es aus), werde ich die Weiterentwicklung des Socialhubs einstellen. Es macht ja keinen Sinn, zwei Addons mit der gleichen oder ähnlichen Funktion parallel zu entwickeln.

Vorteil bei meinem ist übrigens noch, dass man nach Hashtag suchen kann und nicht nur nach Profilen. Ich kenne die Pläne von dir nicht, aber sowas wäre ansonsten noch ein Zusatzfeature für yform.

Gib mir bescheid.

**Comment by dergel** [comment]
Hallo,

mir war nie klar was der socialhub genau macht (hatte auch bei mir leider nie funktioniert) und wir haben yfeed schon ziemlich lange bei uns und beim Kunden laufen und erst jetzt veröffentlich, da wir erst twitter und facebook richtig integriert haben wollten. Hashtags bei twitter gehen bei uns auch, oder meinst du was anderes ? .. Instagramm, pinterest etc wollen wir noch nachziehen. Sollte keine Konkurrenz-AddOn sein, wir brauchten es selbst, hatten es schon lange und haben es leider erst jetzt veröffentlicht. Werden uns um mehr Austausch in z.B. Skype bemühen.

YForm Zusatzfeature ? Am besten direkt dort rein was du genau meinst.

Instagramm.. willst du uns helfen das einzubauen ?

lg

Jan

**Comment by phoebusryan** [comment]
Ich meinte natürlich yfeed, nicht yform. Instagram kann ich gerne integrieren. Ist recht easy.

Was ein nettes Feature wäre (und ich für socialhub auch geplant hatte) wäre ein Abgleich in die andere Richtung. Z.b. dass News, die im Redaxo angelegt werden, automatisch auf Facebook und Twitter gepostet werden. Das passt aber weniger zum Namen "yfeed".

Und bzgl socialhub generell: ja das Ding macht grundsätzlich genau das gleiche. Entwickelt hat es ursprünglich Sascha aber es funktionierte nicht richtig. Ich habe es deshalb von A-Z umgebaut und gefixt.

Ich werde es nun als gute Übung abstempeln und dir in Zukunft hier mit dem yfeed helfen. 

Und bzgl der Parallelentwicklung: das sollte mit FriendsOfRedaxo hoffentlich nicht mehr passieren :-)

**Comment by dergel** [comment]
:) .. toll, dass du helfen willst.. und natürlich auch bloed gelaufen.. nachrichten pushen fände ich auch toll.. aber da gibt es vorher sehr viele dinge zu überlegen.. Sowas wie Zeitplan setzen können etc. Gerne als eigenes Issue ..

**Comment by dergel** [comment]
ich schliesse das "issue" hier..
