### ISSUE TITLE
Nach YForm-Update date-Felder neu initialisieren

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yfeed#16]
Alexander Walther [9:08 AM]  
@dergel beim Update auf YForm 2.0 werden auch die YFeed-Felder `createdate`, etc. deaktiviert. Hier müsste YFeed mit dem nächsten Update diese wieder ordnungsgemäß einrichten.
`date changed_by_user createuser updateuser createdate updatedate`

**Comment by gharlan** [comment]
Verstehe nicht, was das Addon mit yform zu tun hat?

**Comment by tbaddade** [comment]
@gharlan Es gehen angelegte Felder bei einem Update verloren, keine Daten aber dieFelder eben. Deshalb muss man die Felder neu anlegen. Eine Liste welche Valies/Felder betroffen sind, sollte yform zumindest auflisten.

**Comment by gharlan** [comment]
Ich verstehe es trotzdem noch nicht. Wir sind hier im yfeed-Repo, und yfeed hat doch nix mit yform zu tun?

**Comment by alexplusde** [comment]
Das liegt wohl daran, dass ich mich falsch erinnert habe. ich dachte, yfeed legt auch eine yform-Tabelle an, wahrscheinlich habe ich sie in 2 Projekten jeweils zu yform migriert. Da flogen mir die date-Felder raus, weshalb ich annahm, dass yfeed das berücksichtigen sollte...

... muss es aber gar nicht.
