### ISSUE TITLE
Wunsch: Bestimmte Facebook-Posts nicht einlesen

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yfeed#17]
Eine Filterung von Facebook-Posts wäre sehr sinnvoll. 
Evtl. sollen nicht alle Einträge auch auf der Website verarbeitet werden. 
Vielleicht könnte nach einer bestimmten Zeichenfolge gesucht werden (evtl. ein #Hashtag), die dafür sorgt, dass der Eintrag nicht eingelesen wird.

**Comment by alexplusde** [comment]
alias Blacklist / Whitelist.

Wobei: Was spricht dagegen, erst in der Ausgabe zu filtern? Ins SELECT-Statement kannst du ja sagen, welche Zeichenfolge vorkommen/nicht vorkommen darf.

**Comment by dergel** [comment]
sehe ich auch so.. was du mit den eigentlichen Einträgen dann machst - ist ganz dir selbst überlassen.

**Comment by dergel** [comment]
wieder schliessen ?

**Comment by skerbis** [comment]
ok
