### ISSUE TITLE
Invalid OAuth access token signature.

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yfeed#18]
> "Facebook\Exceptions\FacebookResponseException" thrown in /var/www/vhosts/domain.tld/zoff2016/redaxo/src/addons/yfeed/vendor/facebook/php-sdk-v4/src/Facebook/Exceptions/FacebookResponseException.php on line 106
> Invalid OAuth access token signature.
> 
> caused by Facebook\Exceptions\FacebookAuthenticationException in /var/www/vhosts/domain.tld/zoff2016/redaxo/src/addons/yfeed/vendor/facebook/php-sdk-v4/src/Facebook/Exceptions/FacebookResponseException.php on line 106
> Invalid OAuth access token signature.

**Comment by gharlan** [comment]
Der Token wurde nach Anleitung erzeugt?
https://github.com/yakamara/redaxo_yfeed/blob/master/pages/faq.php#L19-L26

**Comment by skerbis** [comment]
Bitte schließen ... habe den Reiter nicht gesehen  unter Einstellungen.

**Comment by alexplusde** [comment]
Der Reiter ist mir auch entgangen. Könnte man die Eingabe bei so wenig Feldern nicht auf einer Seite vornehmen?

**Comment by skerbis** [comment]
Funktioniert aber bestens
