### ISSUE TITLE
Required "app_id" key

### ISSUE THREAD

**Issue by darwin26** [yakamara/redaxo_yfeed#20]
HI,
bin grad am testen... wollte gerade einen Stream einer Facebook Page abholen.
Folgender Fehler erscheint nach Klick auf "Stream abrufen":

 "Facebook\Exceptions\FacebookSDKException" thrown in /htdocs/redaxo/src/addons/yfeed/vendor/facebook/php-sdk-v4/src/Facebook/Facebook.php on line 139
**Required "app_id" key not supplied in config and could not find fallback environment variable "FACEBOOK_APP_ID"**

Habe das auch mit einer APP-ID versucht.. gleicher Fehler...

**Comment by gharlan** [comment]
Sehr merkwürdig. Haben da ja nichts geändert, und bei uns und anderen funktioniert es.

**Comment by darwin26** [comment]
sry... AppId und Secret vergessen -->Settings

*close*
