### ISSUE TITLE
Tweet-URL wird nicht in Feld "url" eingetragen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yfeed#21]

**Comment by gharlan** [comment]
Hmm, aktuell versuchen die Twitter-Streams die erste URL, die im Tweet zu finden ist, [in "url" einzufügen](https://github.com/yakamara/redaxo_yfeed/blob/master/lib/stream/twitter_hashtag.php#L74-L76).
Also die Twitter-Api liefert immer alle URLs die im Tweet vorkommen.
(Allerdings ist da noch ein Fehler drin, daher wird nie eine URL hinzugefügt.)

Ist die Frage, wofür das URL-Feld gedacht ist. Bei Facebook machen wir es auch so. Beispiel:
![screenshot 2017-01-23 18 43 12](https://cloud.githubusercontent.com/assets/330436/22215487/d3daea1a-e19b-11e6-89f4-fd5d6638c33c.png)
URL ist nicht die URL des Facebook-Posts, sondern die URL die drin vorkommt, hier search_it.

Bei Youtube, was ich gerade hinzugefügt habe, habe ich hingegen die Video-URL in URL eingetragen.

Hmm..

ping @tbaddade

**Comment by alexplusde** [comment]
Es wäre in jedem Fall gut, die URL des items (Post, Tweet, Video) verfügbar zu haben, um direkt darauf zu verlinken.

**Comment by gharlan** [comment]
Hmm ja, da sollten wir das URL-Feld wohl am besten aufteilen in zwei Felder.

**Comment by tbaddade** [comment]
Wie @gharlan schon feststellte, soll das die URL innerhalb eines Post sein, nicht die URL des Items. So kann man direkt zum Angebot oder was auch immer verlinken, und spart sich den Umweg über den Dienst. @gharlan schau mal auf der Website unseres Shirt Lieferanten.

**Comment by tbaddade** [comment]
Sämtliche Daten, sollten sich auch in raw wiederfinden.

**Comment by gharlan** [comment]
Habe das mit Jan geklärt, wir werden immer die Orignalurl (Tweet, Facebook-Post, Youtube-Video etc) in das URL-Feld speichern, und kein weiteres Feld einführen.
