### ISSUE TITLE
Cronjob wird nicht ordnungsgemäß ausgeführt.

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yfeed#24]
Wenn ich die Streams direkt im Addon abrufe, funktioniert alles. Beim Cronjob hingegen hagelt es Fehler.

```
19.01.2017 00:06:46	yFeed	2 errors (Facebook, Twitter), 2 items added, 0 items updated, 0 items not updated because changed by user
```

**Comment by gharlan** [comment]
> Beim Cronjob hingegen hagelt es Fehler.

Du meinst "nur" die errors in der Log-Message, oder hast du auch noch andere Errors?

**Comment by gharlan** [comment]
Und ist das allgemein bei dir bei dem Cronjob, oder nur beim Cronjob über die "Skript-Umgebung", also über bin/run?

**Comment by alexplusde** [comment]
Allgemein. Nur die Fehler, die auch ins Log wandern.

**Comment by gharlan** [comment]
Über bin/run kann ich es nachvollziehen, Cronjob übers Backend nicht, dort funktioniert es bei mir.

**Comment by alexplusde** [comment]
Wie kann ich das debuggen?

**Comment by gharlan** [comment]
Mit dem Fix (siehe Commit hier drüber) funktioniert es bei mir jetzt auch mit den bin/run-Cronjobs.

Bei mir funktionierten übrigens Twitter-Streams überhaupt nicht mehr, egal ob über Cronjob oder nicht. Nach Update der Twitter-Lib klappt es aber bei mir wieder (hab ich bereits commitet).

**Comment by gharlan** [comment]
Probiere mal bitte diese Version: https://redaxo.org/files/addon_yfeed_1.1.0-alpha1.zip

**Comment by gharlan** [comment]
Im Installer gibt es nun eine 1.1-beta1, bitte mit der mal testen.

**Comment by alexplusde** [comment]
Gerade in die Logs geschaut - schein durchgehend zu funktionieren.
