### ISSUE TITLE
Class 'TwitterOAuth\Auth\ApplicationOnlyAuth' not found

### ISSUE THREAD

**Issue by georgkaser** [yakamara/redaxo_yfeed#25]
Hallo,

ich bekomm folgenden Fehler wenn ich versuche meine Twitter Einträge zu aktualisieren:

redaxo/src/addons/yfeed/lib/stream/twitter_user_timeline.php on line 56
Class 'TwitterOAuth\Auth\ApplicationOnlyAuth' not found

Fehlt da was - oder wie? Version 1.1.0-beta1

**Comment by georgkaser** [comment]
Also bei der alten Version gabs nen vendor Ordner, der ist jetzt weg. Wenn ich den von der Version 1.0 reinkopier, dann ist der Fehler weg.

**Comment by gharlan** [comment]
Ja sorry, habe eine neue beta2 rausgebracht, wo der Ordner enthalten ist.

**Comment by georgkaser** [comment]
Ah, cool - danke!
