### ISSUE TITLE
Instagram funktioniert nicht mehr..

### ISSUE THREAD

**Issue by phoebusryan** [yakamara/redaxo_yfeed#38]
... ist das möglich? Gabs ein Update? Von einem Tag auf den anderen gibts einfach nichts mehr zurück.

**Comment by tbaddade** [comment]
von @gharlan via Slack 

> da das mit den api keys so nervig ist bei insta, hatte ich die variante “ohne” eingebaut. die nutzt aber eine nicht offizielle “api” (wird von der website genutzt), daher ist es schon gut möglich, dass sie die geändert haben.
Jupp so ist es. Um diese nicht-offizielle Api zu nutzen, nutzt yfeed eine bibliothek. dort wurde es auch schon bemerkt: https://github.com/Bolandish/PHP-Instagram-Grabber/issues/40
Bleibt also nur entweder api key in yfeed hinterlegen, dann nutzt es die offizielle api, oder dafür sorgen, dass das issue dort gelöst wird, dann kann ich das updaten.

**Comment by DonLoron** [comment]
ich denke nicht, dass sich das lösen wird, von wessen Seite her auch immer. Einzige Lösung ist ein API Key zu hinterlegen, ich würde dieses Issue bis auf weiteres schliessen.

**Comment by phoebusryan** [comment]
Interessant, es gibt hier eine Lösung:
https://github.com/Bolandish/PHP-Instagram-Grabber/issues/40#issuecomment-310102664

Bzgl. API: Da gibts kein Accesstoken. Habs stundenlang probiert. Wenn man auf Instagram einen Accesstoken generieren will "I want to display hashtag content and public content on my website."

... kommt die Meldung: 

> This use case is not supported. We do not approve the public_content permission for one-off projects such as displaying hashtag based content on your website. As alternative solution, you can show your own Instagram content, or find a company that offers this type of service (content discover, moderation, and display).
