### ISSUE TITLE
weitere Streams registrieren

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yfeed#42]
Wie kann ich eigene Streams aus einem Addon / Plugin heraus in YFeed registrieren?

**Comment by gharlan** [comment]
Sorry für die späte Antwort!

Das geht so:

```php
rex_yfeed_stream::addStream(my_stream_class::class, 'short_name');
```

**Comment by alexplusde** [comment]
Danke @gharlan 

4 Tage sind doch nichts :)

**Comment by gharlan** [comment]
Huch, irgendwie dachte ich, das Issue wäre viel älter. Keine Ahnung, wie ich zu der Annahme kam. :)
