### ISSUE TITLE
Ooops nach Update auf 1.1.2/ Instagram User Stream

### ISSUE THREAD

**Issue by IngoWinter** [yakamara/redaxo_yfeed#45]
Nach Update von 1.1.0 auf 1.1.2 per Installer bekomme ich im Ooops die Instagram API Fehlermeldung "This client has not been approved to access this resource."
Userid gegen Username auszutauschen hat nix geholfen, gleiche Fehlermeldung.

**Comment by gharlan** [comment]
Nutzt du Instagram mit Access Token oder ohne?

**Comment by IngoWinter** [comment]
Mit Access Token

**Comment by gharlan** [comment]
Wahrscheinlich löst es das nicht, aber probiere mal bitte, ob dies etwas ändert: https://github.com/yakamara/redaxo_yfeed/commit/c300b1ffa3715187adb00a9f7d41f8f543c47af6

Ansonsten: Kannst du hier (oder mir in Slack) einen Screenshot von der ganzen Fehlerseite schicken, also insbesondere mit Stacktrace?

**Comment by IngoWinter** [comment]
Der geänderte Regex hat nicht geholfen. Ich hab die einen Screenshot per Slack geschickt.

**Comment by gharlan** [comment]
Mit Info auf Slack weiter geschaut. Mit der Regex-Änderung oben funktioniert es zumindest wieder, wenn man die User-ID einträgt (auch wenn das Feld inzwischen Benutzername heißt).

Scheinbar braucht man bei der Variante mit Benutzername erweiterte Rechte auf den Account.
Muss ich mal schauen, wie ich das löse. Eventuell muss ich es dann so machen, dass man bei Nutzung der inoffiziellen Api den Benutzernamen eintragen muss (denn da geht nur noch die Variante), bei der offiziellen (mit Access Token) hingegen die Benutzer-ID.

**Comment by gharlan** [comment]
Ist erst mal gelöst, mit entsprechendem Hinweis, wann man was nutzen muss (Benutzer-ID vs Benutzername)
