### ISSUE TITLE
Export / Import der YFeed-Stream-Tabelle schlägt fehl

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yfeed#46]
Beim Importieren eines Redaxo-Exports schlägt der Import von rex_yfeed_stream fehl.

**Comment by gharlan** [comment]
Mit welcher Version des backup-Addons wurde der Export erstellt?
Denn das wurde eigentlich im Februar gefixt, in backup 2.0.4

**Comment by gharlan** [comment]
Siehe auch https://github.com/yakamara/redaxo_yfeed/issues/22 ;)

**Comment by alexplusde** [comment]
Oh :D. Hatte ich nicht mehr auf dem Schirm. Redaxo 5.2, also vermutlich vor backup 2.0.4.

close?
