### ISSUE TITLE
Instagram public_content Error

### ISSUE THREAD

**Issue by VIEWSION** [yakamara/redaxo_yfeed#50]
Scheint als ob Instagram den API Zugriff gewaltig eingeschränkt hat. Seit 1. Oktober gibt es wohl nur noch Apps/Tokens mit "basic" Scope. Also keine Möglichkeit mehr ausserhalb von seinem eigenen Profil was zu suchen. Schade... jemand einen Workarround? Ich bräuchte die #49 Tag-Suche...

... übrigens... vielen Dank dafür! Hatte yfeed gar nicht auf dem Schirm - ist aber genau was ich brauche :)

**Comment by gharlan** [comment]
Wenn man den Weg über die offizielle API geht (sobald Access Token hinterlegt), dann muss der Token über eine Instagram App erzeugt worden sein, die durch deren Review ging, um keine Einschränkungen zu haben. Einen solchen Token kann man sich zum Beispiel hier erzeugen: http://instagram.pixelunion.net (Falls man denen vertraut, aber deren App ist nun mal "approved").

Alternativ kann man in YFeed den Access Token ganz weglassen. Dann wird eine inoffzielle Api verwendet. Großer Nachteil: Die ändert sich öfters, und dann geht es erst mal wieder nicht.
Aktuell geht es aber (mit der YFeed-Version 1.2.1 von heute).

**Comment by VIEWSION** [comment]
Super! Klappt wieder... wäre vielleicht hilfreich wenn man noch manuell für den Feed festlegen könnte ob man die offizielle oder inoffizielle API nutzen möchte. Der Benutzer-Feed klappt ja mit dem Standard-Token... nur wenn man gleichzeitig einen Tag-Feed abrufen will, geht das nicht wenn der eingetragen ist. Der "inoffizielle" Tag-Feed Abruf läuft relativ simpel über einen JSON Abruf ohne Anmeldung ab (z.B. https://www.instagram.com/explore/tags/silvester/?__a=1 ) - da ist es recht wahrscheinlich dass das weiterhin so bleibt... bei den Sachen mit Anmeldung ist das schon problematischer...

**Comment by gharlan** [comment]
> wäre vielleicht hilfreich wenn man noch manuell für den Feed festlegen könnte ob man die offizielle oder inoffizielle API nutzen möchte

Mach dazu am besten mal ein neues Issue auf, sonst geht der Wunsch verloren.

**Comment by VIEWSION** [comment]
...übrigens - ich habe mal einen Token über pixelunion generiert... scheint nicht mehr zu funktionieren: "This client has not been approved to access this resource." Ich habe es auch schon mit einem selbst erstellten Token versucht - aber da klappt es eben mit der Hashtag-Suche nicht. Nur der User Feed geht.... naja - hoffen wir mal dass die inoffizielle Version weiterhin funktioniert ;)
