### ISSUE TITLE
FAQs -> Doku

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yfeed#53]
@dergel auch hier würde ich gerne die Doku ausbauen, unter anderem mit einem Experten-Beispiel, wie man eigene Feeds registrieren kann.

Wie wäre es denn gewünscht, einfach wieder als MD-Datei hier reinhauen?

**Comment by dergel** [comment]
fände ich gut..  schau mal bei yrewrite wegen der doku wie ich das gemacht habe .. finde die lösung eigentlich ganz cool.. ist anders als bei yform. nur eine lange datei. alle h2 sind und h3s kommen in die navigation und splitten die eine große dokudatei.. release von yrewrite kommt heute, kannst du dir dann direkt ansehen

**Comment by alexplusde** [comment]
@dergel ok, schau ich mir mal an.

**Comment by alexplusde** [comment]
Hab jetzt was dazu gemacht.

Bitte noch hier eine bessere Beschreibung verwenden:
![image](https://user-images.githubusercontent.com/3855487/51382819-165efe00-1b18-11e9-8657-c23346f16d09.png)

z.B. `Ein REDAXO5-AddOn zum Abruf externer Feeds`
