### ISSUE TITLE
Instagram Bilder gehen nicht mehr

### ISSUE THREAD

**Issue by VIEWSION** [yakamara/redaxo_yfeed#58]
... anscheinend hat Instagram den Abruf der Bilder über die "alternative API" gesperrt: Access Denied. Gibt es schon einen Workaround? Die offizielle API kann ich leider nicht verwenden, weil das da mit der Hashtag-Suche nicht funktioniert.

**Comment by VIEWSION** [comment]
wurde da schon gefixed.. https://github.com/postaddictme/instagram-php-scraper/commit/057de02f8dbfdd6f4a3eda42aaf4613705aabd4d - muss nur noch upgedated werden

**Comment by tbaddade** [comment]
> muss nur noch upgedated werden

Erstellst du einen PR @VIEWSION ?

**Comment by VIEWSION** [comment]
sorry... war im Urlaub ;) es sollte reichen die Version von instagram-php-scraper zu aktualisieren. Im letzten Release (0.8.17) https://github.com/postaddictme/instagram-php-scraper/releases/tag/v0.8.17 ist der Fix enthalten. Kann das bitte jemand von Euch machen? Ich bin mir da etwas unsicher... Muss die composer.json und composer.lock angepasst werden?
